---
- hosts: all

  tasks:
    - name: update node PPA repo
      sudo: yes
      shell: curl -sL https://deb.nodesource.com/setup_4.x | sudo bash -
  
    - name: Install nodejs
      sudo: yes
      apt: pkg=nodejs force=yes

    - name: Install build-essential
      sudo: yes
      apt: pkg=build-essential force=yes

    - name: Installing git
      sudo: yes
      apt: pkg=git force=yes

    - name: Installing vim
      sudo: yes
      apt: pkg=vim force=yes

    - name: Install Ultimate vim config
      sudo: no
      shell: curl http://j.mp/spf13-vim3 -L -o - | sh
      args:
        creates: /home/vagrant/.spf13-vim-3/.vimrc

    - name: Installing Silver Searcher
      sudo: yes
      apt: pkg=silversearcher-ag force=yes

    - name: Installing tmux
      sudo: yes
      apt: pkg=tmux force=yes

    - name: Get my config for tmux
      get_url: url=https://dl.dropboxusercontent.com/u/27226292/dot_files/tmux.conf dest=~/.tmux.conf

    - name: Installing gulp
      sudo: yes
      npm: name=gulp global=yes

    - name: Installing slush scaffolding system
      sudo: yes
      npm: name=slush global=yes

    - name: Installing slush-js-skeleton
      sudo: yes
      npm: name=slush-js-skeleton global=yes

    - name: Installing jsVerify
      sudo: yes
      npm: name=jsverify global=yes

    - name: Installing Ramda
      sudo: yes
      npm: name=ramda global=yes

    - name: Update npm
      sudo: no
      command: npm install chdir=~/proj

